# Generated by Django 6.1.1 on 2026-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_researchproject_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
