# Generated by Django 6.1.1 on 2026-10-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_projects', to='core.category'),
        ),
    ]
