# Generated by Django 6.1.1 on 2026-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant (accueil)'),
        ),
    ]
